
backend:
  name: github
  repo: tonedela/AuthoringTest
  Callback URL: https://tonedela.github.io/AuthoringTest/admin/
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "items"
    label: "Items"
    format: "json"
    files:
      - file: "data/items.json"
        label: "Item List"
        name: "items"
        fields:
          - label: "Items"
            name: ""
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Price", name: "price", widget: "number"}
              - label: "Tags"
                name: "tags"
                widget: "list"
                field: {label: "Tag", name: "tag", widget: "string"}
